vich_uploader:
    db_driver: orm
    metadata:
        type: attribute 
    mappings:
       biens:
            uri_prefix: /images/biens
            upload_destination: '%kernel.project_dir%/public/images/biens'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

           
